### ISSUE TITLE
nullpointer in controller 

### ISSUE THREAD

**Issue by lolo8304** [cordalo-ch/cordalo-template#12]
if no object is found in search there is an exception in rendering "null" into an json structure

java.lang.NullPointerException: null
	at ch.cordalo.corda.common.client.webserver.StateBuilder.self(StateBuilder.java:152) ~[corda-common-client-0.11-SNAPSHOT.jar:?]
	at ch.cordalo.template.client.webserver.ControllerCar.getResponse(ControllerCar.java:60) ~[main/:?]
	at ch.cordalo.template.client.webserver.ControllerCar.searchCar(ControllerCar.java:160) [main/:?]

checkout "getResponse" method

**Comment by lolo8304** [comment]
done - implemented. moved code into #2000
